name: Docker Image CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag discoursegraphs
    - name: run pytest in Docker
      run: docker run --entrypoint=pytest discoursegraphs
